from fastapi import APIRouter, Depends, status, HTTPException
from sqlalchemy.orm import Session
from app.backend.db_depends import get_db
from typing import Annotated
from app.models import user
from sqlalchemy import insert, select, delete, update
from app.schemas import CreateUser, UpdateUser

from slugify import slugify

router = APIRouter(prefix='/user', tags=['user'])


@router.get('/')
async def all_users(db: Annotated[Session, Depends(get_db)]):
    users_all = db.scalars(select(user.User)).all()
    return users_all

@router.get('/user_id')
async def user_by_id(db: Annotated[Session, Depends(get_db)], user_id: int):
    try:
        user_with_id = db.scalars(select(user.User).where(user.User.id == user_id))
        return user_with_id
    except IndexError:
        raise HTTPException(status_code=404, detail='Message Not found')

@router.post('/create')        # Здесь надо еще проверить на наличие такого юзера в базе. Вдруг он уже есть.
async def create_user(db: Annotated[Session, Depends(get_db)], create_user: CreateUser):
    db.execute(insert(user.User).values(username=create_user.username, firstname=create_user.firstname,
                                        lastname=create_user.lasttname, age=create_user.age))
    db.commit()
    return {'status_code': status.HTTP_201_CREATED, 'transaction': 'Successful'}



@router.put('/update')
async def update_user(db: Annotated[Session, Depends(get_db)]):
    pass


@router.delete('/delete')
async def delete_user(db: Annotated[Session, Depends(get_db)]):
    pass
